In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])

In [7]:
ser2 = Series([3, 4], index=['X', 'Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis=1, sort=True)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [17]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [18]:
dframe1

X         Y         Z
0  0.239055  0.486023  1.854690
1 -0.483227  1.411965 -0.741183
2  1.715020  1.204272 -0.839478
3  0.342693  0.560516  0.776266

In [19]:
dframe2

Y         Q         X
0  0.818759 -0.160869  1.871904
1  0.467297  1.297266  0.637607
2 -1.668601  1.151355 -0.442503

In [21]:
pd.concat([dframe1, dframe2], sort=True)

Q         X         Y         Z
0       NaN  0.239055  0.486023  1.854690
1       NaN -0.483227  1.411965 -0.741183
2       NaN  1.715020  1.204272 -0.839478
3       NaN  0.342693  0.560516  0.776266
0 -0.160869  1.871904  0.818759       NaN
1  1.297266  0.637607  0.467297       NaN
2  1.151355 -0.442503 -1.668601       NaN

In [22]:
pd.concat([dframe1, dframe2], ignore_index=True, sort=True)

Q         X         Y         Z
0       NaN  0.239055  0.486023  1.854690
1       NaN -0.483227  1.411965 -0.741183
2       NaN  1.715020  1.204272 -0.839478
3       NaN  0.342693  0.560516  0.776266
4 -0.160869  1.871904  0.818759       NaN
5  1.297266  0.637607  0.467297       NaN
6  1.151355 -0.442503 -1.668601       NaN