In [3]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# square roots

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
# exponential operations - what are the strange 1.00000000e+00-like numbers?

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
# Binary functions

In [10]:
A = np.random.randn(10)
A

array([-1.66090227, -1.27908204, -0.17120445, -1.08018232,  0.21918985,
       -0.88469553, -0.38926855, -0.23772931,  0.11778734, -0.60351378])

In [11]:
B = np.random.randn(10)
B

array([-0.9774779 , -0.33921637,  0.2307507 , -0.93457072, -0.08616454,
       -1.03836325, -0.42037093, -1.30845657,  2.03970965,  1.11322073])

In [12]:
np.add(A,B)

array([-2.63838017, -1.61829841,  0.05954625, -2.01475304,  0.13302531,
       -1.92305878, -0.80963948, -1.54618588,  2.15749699,  0.50970695])

In [13]:
np.maximum(A,B)

array([-0.9774779 , -0.33921637,  0.2307507 , -0.93457072,  0.21918985,
       -0.88469553, -0.38926855, -0.23772931,  2.03970965,  1.11322073])

In [14]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser

webbrowser.open(website)

True