In [12]:
import numpy as np

In [13]:
my_list1 = [1,2,3,4]

In [14]:
my_array1 = np.array(my_list1)

In [15]:
my_array1

array([1, 2, 3, 4])

In [23]:
my_list2 = [11,22,33,44]

In [24]:
my_lists = (my_list1, my_list2)

In [25]:
my_array2 = np.array(my_lists)

In [26]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [27]:
my_array2.shape

(2, 4)

In [29]:
my_array2.dtype

dtype('int64')

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
my_zeros_array = np.zeros(5)

In [32]:
my_zeros_array.dtype

dtype('float64')

In [33]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# How come? Why do I get 1.? Should be 0.

In [35]:
empty_array = np.empty(5)

In [36]:
empty_array.dtype

dtype('float64')

In [52]:
np.empty(4)

array([6.89920110e-310, 6.89916190e-310, 6.89920106e-310, 6.89916190e-310])

Why do I get such numbers in empty array?
there should be 0.

In [46]:
from __future__ import division

In [47]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [1]:
np.empty?

Object `np.empty` not found.
